openapi: 3.0.0
info:
  title: Kling AI视频生成平台接口
  version: 1.0.0
  description: 基于Kling AI API的视频生成中间件接口设计

servers:
  - url: https://api.yourdomain.com/v1
    description: 生产环境

tags:
  - name: Tasks
    description: 视频生成任务管理
  - name: Results
    description: 生成结果管理
  - name: History
    description: 任务历史记录

paths:
  /text2video:
    post:
      tags: [Tasks]
      summary: 创建视频生成任务
      description: 提交生成请求并返回任务ID
      security:
        - JwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        '202':
          description: 任务已接受
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '400':
          description: 参数校验失败
        '429':
          description: 请求频率超限

  /text2video/{task_id}/result:
    get:
      tags: [Results]
      summary: 查询任务状态
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 当前任务状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          description: 任务不存在

  /text2video/history:
    get:
      tags: [History]
      summary: 获取任务历史
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: 历史记录列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskHistoryItem'

components:
  schemas:
    TaskRequest:
      type: object
      required: [prompt]
      properties:
        prompt:
          type: string
          maxLength: 2500
          example: "赛博朋克风格的城市夜景，霓虹灯闪烁，飞行汽车穿梭"
        negative_prompt:
          type: string
          maxLength: 2500
          example: "低分辨率，模糊"
        mode:
          type: string
          enum: [std, pro]
          default: std
        aspect_ratio:
          type: string
          enum: [16:9, 9:16, 1:1]
          default: 16:9
        duration:
          type: integer
          enum: [5, 10]
          default: 5

    TaskStatusResponse:
      description: 视频生成任务的状态模式
      type: object
      properties:
        status:
          type: string
          enum: [uploading, preprocessing, rendering, postprocessing, completed]
        current_stage_progress:
          type: number
          format: float
          minimum: 0
          maximum: 100
        debug_info:
          type: object
          properties:
            render_frames:
              type: integer
            gpu_utilization:
              type: number

    TaskHistoryItem:
      type: object
      properties:
        task_id:
          type: string
        status:
          type: string  
        created_at:
          type: string
          format: date-time
        # 新增文生视频请求参数
        model_name:
          type: string
        prompt:
          type: string
        negative_prompt:
          type: string
        cfg_scale:
          type: number
        mode:
          type: string
          enum: [std, pro]
        aspect_ratio:
          type: string
          enum: [16:9, 9:16, 1:1]
        duration:
          type: string
        external_task_id:
          type: string
        # 新增文生视频结果
        video_url:
          type: string
        video_duration:
          type: integer

  securitySchemes:
    JwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "使用 JWT 进行身份验证，需要在请求头中添加 `Authorization: Bearer <token>`"