openapi: 3.0.0
info:
  title: 图像生成前端API
  description: 用户与后端交互生成图片
  version: 1.0.0
servers:
  - url: /
tags:
  - name: ImageGeneration
    description: 图像生成任务
  - name: ImageResults
    description: 图片结果查询
  - name: History
    description: 任务历史记录
paths:
  /create-image:
    post:
      summary: 发起图像生成请求
      description: 用户输入参数，调用后端生成图片
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                model_name:
                  type: string
                  description: 模型名称，枚举值：kling-v1, kling-v1-5, kling-v2，默认值kling-v1
                prompt:
                  type: string
                  description: 正向文本提示词，必填，不能超过2500个字符
                negative_prompt:
                  type: string
                  description: 负向文本提示词，可选，不能超过2500个字符；图生图场景下不支持
                image:
                  type: string
                  description: 参考图像，支持Base64编码或图片URL，Base64编码时无前缀
                image_reference:
                  type: string
                  description: 图片参考类型，枚举值：subject, face；仅kling-v1-5且image不为空时必填
                image_fidelity:
                  type: number
                  description: 生成过程中对用户上传图片的参考强度，取值范围：[0,1]，默认值0.5
                human_fidelity:
                  type: number
                  description: 面部参考强度，仅image_reference为face时生效，取值范围：[0,1]，默认值0.45
                n:
                  type: integer
                  description: 生成图片数量，取值范围：[1,9]，默认值1
                aspect_ratio:
                  type: string
                  description: 生成图片的画面纵横比，枚举值：16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3, 21:9，默认值16:9
                callback_url:
                  type: string
                  description: 本次任务结果回调通知地址，可选
      responses:
        200:
          description: 成功提交请求
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 错误码，0表示成功
                  message:
                    type: string
                    description: 错误信息
                  request_id:
                    type: string
                    description: 请求ID，系统生成，用于跟踪请求、排查问题
                  data:
                    type: object
                    properties:
                      task_id:
                        type: string
                        description: 任务ID，系统生成
        400:
          description: 参数填写错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 错误码
                  message:
                    type: string
                    description: 错误信息
  /create-image/{task_id}/result:
    get:
      tags: [ImageResults]
      summary: 获取生成图片状态
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 当前任务状态
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          description: 任务不存在
  /create-image/history:
    get:
      tags: [History]
      summary: 获取图片生成任务的历史记录
      description: 查询图片生成任务的历史记录，支持分页查询。
      security:
        - JwtAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
          description: 每页显示的记录数量
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: 记录偏移量
      responses:
        '200':
          description: 历史记录列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImageTaskHistoryItem'
        '401':
          description: 未授权访问
components:
  schemas:
    TaskStatusResponse:
      description: 图片生成任务的状态模式
      type: object
      properties:
        status:
          type: string
          enum: [uploading, preprocessing, rendering, postprocessing, completed]
        current_stage_progress:
          type: number
          format: float
          minimum: 0
          maximum: 100
        debug_info:
          type: object
          properties:
            render_frames:
              type: integer
            gpu_utilization:
              type: number
    ImageTaskHistoryItem:
      description: 图片生成任务的历史记录项
      type: object
      properties:
        task_id:
          type: string
          example: "img_abc123"
        created_at:
          type: string
          format: date-time
          description: 任务创建时间
        status:
          type: string
          enum: [uploading, preprocessing, rendering, postprocessing, completed, failed]
          description: 任务最终状态
        model_name:
          type: string
          description: 模型名称，枚举值：kling-v1, kling-v1-5, kling-v2
        prompt:
          type: string
          description: 正向文本提示词
        negative_prompt:
          type: string
          description: 负向文本提示词
        image:
          type: string
          description: 参考图像，支持Base64编码或图片URL，Base64编码时无前缀
        image_reference:
          type: string
          description: 图片参考类型，枚举值：subject, face
        image_fidelity:
          type: number
          description: 生成过程中对用户上传图片的参考强度，取值范围：[0,1]
        human_fidelity:
          type: number
          description: 面部参考强度，仅image_reference为face时生效，取值范围：[0,1]
        n:
          type: integer
          description: 生成图片数量，取值范围：[1,9]
        aspect_ratio:
          type: string
          description: 生成图片的画面纵横比，枚举值：16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3, 21:9
        image_urls:
          type: array
          items:
            type: string
            format: uri
          description: 生成图片的访问链接
  securitySchemes:
    JwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "使用 JWT 进行身份验证，需要在请求头中添加 `Authorization: Bearer <token>`"